### ISSUE TITLE
SVG和Git组合使用

### ISSUE THREAD

**Issue by shanejixx** [shanejixx/shanejixx.github.io#20]
### 前言

很多公司用的版本控制工具是SVN

稍微了解了下Git和SVN的区别

SVN

- 集中式
- 中心化，服务器永远只有一个最新版本

Git

- 分布式
- 去中心化，各个用户手中可以有多个版本，集中做版本合并

Git和SVN的工作流

SVN（TortoiseSVN）

- SVN checkout拉取
- SVN commit提交
- SVN update更新
- 冲突

Git

- git clone 拉取
- git add .提交到缓存区
- git commit -m 'xxx'本地提交
- git push提交到远程
- git pull更新
- 冲突

### 场景

公司通过SVN checkout拉取代码，本地增删查改，然后SVN commit提交

然后回到家中想起来有bug需要修改，没得办法，可行的方法是：

- 自己带个u盘每天下班后，拿着拷贝一份，插上家中的电脑，吧备份完成后，更新u盘，上班后继续带上从家中拿来的u盘拷贝
- 上述方法，繁琐，可行性不高，可以用SVN或者Git

基于上面的想法，得出如下实践：

在公司：

- SVN checkout拉取代（或者SVN update更新）公司电脑的代码
- 增删改查后，SVN commit提交，git push推送到自己的私有仓库（GitHub）

在家中：

- git clone（或者 git pull）拉取或者更新家中电脑的代码
- 增删改查后git push推送到自己的私有仓库（GitHub）

### 实现

其实非常简单，实现思路：

- git 中忽略SVN的配置项
- SVN中忽略git的配置项

自己实践了下，确实可以

**Comment by Mulai-1997** [comment]
请问下
git中加载SVN的配置项
SVN中加载git的配置项
具体怎么操作，纯小白，百度没找到方法
